### ISSUE TITLE
ActionChains Issue

### ISSUE THREAD

**Issue by Guillaume-3si** [AdiuvoDotFr/Kissenium#12]
Hi,
I currently try to use mouse interaction in Kissenium, but it seem dont work properly:

When I try a simple command like 
            **Action = ActionChains(self.selenium.browser)
            Action.move_to_element(BTN_SUPPR)
            Action.click(BTN_SUPPR)
            Action.perform()**

I can see it's just hi-light the button in hi-right of the Chrome window.

If u got an idea... Thank you

Guillaume

**Comment by AdiuvoDotFr** [comment]
I've tried to do it and it seems to work correctly.

Have you tried to use `self.selenium.click_first_xpath` or `self.selenium.click_id` ? 

Please tell me if it work or not. Then we might try something else

Also, it is not recommended to use variables in [camel case](https://en.wikipedia.org/wiki/Camel_case) in python. Camel case is used for class names

**Comment by AdiuvoDotFr** [comment]
Hi, is this still an issue? If not please this issue. Else, please give me some informations.

**Comment by Guillaume-3si** [comment]
Problem solve, thank you!
